### ISSUE TITLE
feat: Secret Square API

### ISSUE THREAD

**Issue by ojj1123** [AboutClan/Backend#187]
follow up https://github.com/AboutClan/About/pull/185

## TODO

- [x]  글 등록 API - POST /square
- [x]  글 삭제 API - DELETE /square/[id]
- [x]  글 목록 가져오기 API - GET /square
- [x]  글 상세 가져오기 API - GET /square/[id]
- [x]  댓글 등록 API - POST /square/comment
- [x]  댓글 삭제 API - DELETE /square/[squareId]/comment/[commentId]
- [x]  투표 API - PATCH /square/[id]/poll
- [x]  현재 투표 상태 API - GET /square/[id]/poll
- [x]  좋아요 추가 API - PUT /square/[id]/like
- [x]  좋아요 취소 API - DELETE /square/[id]/like
- [ ] swagger 작성
- [x] error handling (http method and status code)
- [x] validate for body, query or url params
